#! /usr/bin/env node

'use strict';

const _ = require('lodash');
const fs = require('fs');
const path = require('path');

const error = console.error.bind(this);
const log = console.log.bind(this);
const info = console.info.bind(this);

const shell = require('shelljs');
const entryPwd = shell.pwd().stdout;

function init(currentDir) {
  const pwd = shell.pwd().stdout;
  currentDir = currentDir || '.';
  shell.cd(currentDir);

  // -- recurse
  submodules().forEach(function(submodule) {
    gitSubmoduleInit(submodule);
    gitSubmoduleUpdate(submodule);
    init(submodule)
  });

  npmLinkSubmodules(path.join(pwd, currentDir));
  shell.cd(pwd);
}

function gitSubmoduleInit(submodule) {
  submodule = submodule || '.';
  shell.exec('git submodule init ' + submodule);
}

function gitSubmoduleUpdate(submodule) {
  submodule = submodule || '.';
  shell.exec('git submodule update ' + submodule);
}

function npmLinkSubmodules(currentDir) {
  submodules().forEach(function(submodule) {
    shell.exec('cd ' + submodule + ' && yarn link');
    shell.exec('cd ' + submodule + ' && yarn install');

    try {
      const module = JSON.parse(fs.readFileSync(path.join(currentDir, submodule, 'package.json')));
      log('module name:', module.name);

      // shell.exec('cd ' + entryPwd + ' && yarn link ' + module.name);
      shell.exec('cd ' + currentDir + ' && yarn link ' + module.name);

      // TODO: Check if module is already linked
      // Error if it is and it's a different refspect or commit hash
    } catch (err) {
      // error(err.message);
      // error(err.stack);
      throw new Error(err);
    }
  })
}

function submodules() {
  return _.compact(
    shell
      .exec('git submodule')
      .stdout
      .split('\n')
      .map(function(line) {
        if (/(^\s*$)|(storj-base)/.test(line)) return;

        return line.match(/.\w+\s(\S+)/)[1];
      })
  )
}

exports.init = init;
