#! /usr/bin/env node

'use strict';

const _ = require('lodash');
const fs = require('fs');
const path = require('path');

const shell = require('shelljs');
const entryPwd = shell.pwd().stdout;

function init(currentDir) {
  const pwd = shell.pwd().stdout;
  currentDir = currentDir || '.';
  shell.cd(currentDir);

  // -- recurse
  submodules().forEach(function(submodule) {
    init(path.join(currentDir, submodule))
  });

  npmLinkSubmodules(currentDir);
  shell.cd(pwd);
}


function npmLinkSubmodules(currentDir) {
  submodules().forEach(function(submodule) {
    const submoduleDir = path.join(currentDir, submodule);

    shell.exec('cd ' + submoduleDir + ' && yarn link && yarn install --ignore-engines');

    try {
      const module = JSON.parse(fs.readFileSync(path.join(submoduleDir, 'package.json')));

      shell.exec('cd ' + entryPwd + ' && yarn link ' + module.name);

      // TODO: Check if module is already linked
      // Error if it is and it's a different refspect or commit hash
    } catch (err) {
      error(err.message);
      error(err.stack);
      throw new Error(err);
    }
  })
}

function submodules() {
  return _.compact(
    shell
      .exec('git submodule')
      .stdout
      .split('\n')
      .map(function(line) {
        if (/^\s*$/.test(line)) return;

        return line.match(/.\w+\s(\S+)/)[1];
      })
  )
}

exports.init = init;
